site_name: RTM
site_url: 'https://xhan0703.github.io/rtmdoc'
site_description: 'RTM documentation for users and developers.'
site_author: 'TransLink Forecasting'
repo_url: 'https://github.com/xhan0703/rtmdoc/'
edit_uri: ""
copyright: 'Copyright &copy; 2020 TransLink Forecasting'
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
nav:
    - 'User Guide':
            - workflow.md
            - data_outputs.md
            - data_analysis.md
            - data_generate.md
            - appendix.md
    - About:
            - about/contributing.md
            # - about/release-notes.md
            # - about/license.md
extra_css:
    - css/extra.css
markdown_extensions:
    -
        toc:
            permalink: true
    - admonition
    - def_list
plugins:
    - search
google_analytics:
    - ""
    - auto
