site_name: RTM
site_url: 'https://translinkforecasting.github.io/rtmdoc'
site_description: 'RTM documentation for users and developers.'
site_author: 'TransLink Forecasting'
repo_url: 'https://github.com/TransLinkForecasting/rtmdoc'
edit_uri: ""
copyright: 'Copyright &copy; 2020 TransLink Forecasting'
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
nav:
    - 'User Guide':
            - workflow.md
            - adv_inputs.md
            - data_outputs.md
            - data_analysis.md
            - data_generate.md
            - scenario_comparison.md
    - 'Developer Guide':
            - dev_getting_started.md
            - coding_standard.md
    - 'References':
            - reports.md
            - naming_conventions.md
            - data_assumptions.md
    - About:
            - about/contributing.md
            # - about/release-notes.md
            # - about/license.md
extra_css:
    - css/extra.css
markdown_extensions:
    - toc:
            permalink: true
    - attr_list
    - admonition
    - def_list
plugins:
    - search
google_analytics:
    - ""
    - auto
